console.log("Binevenidos al infierno :)")
requires("./1.counter")
requires("./2.hell")
requires("./3.Js_is_not_fun")
requires("./4.more_errors")
requires("./5.monster_error")
requires("./6.write_to_teacher")